name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/collectionbox
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out workflow repository
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.repository.default_branch }}
      - name: Build and publish package

        uses: ./.github/actions/publish-pypi
        with:
          ref: ${{ github.event.release.tag_name }}
